""" base_GUI.py --

 UI generated by GUI Builder Build 146 on 2018-04-23 10:26:02 from:
    C:/Users/chris/Desktop/CYEN PROJ/base_GUI.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from base_GUI_ui import Base_GUI

# BEGIN USER CODE global

# END USER CODE global

class CustomBase_GUI(Base_GUI):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _button_2_command --
    #
    # Callback to handle _button_2 widget option -command
    def _button_2_command(self, *args):
        pass

    # _checkbutton_1_command --
    #
    # Callback to handle _checkbutton_1 widget option -command
    def _checkbutton_1_command(self, *args):
        pass

    # _entry_1_invalidcommand --
    #
    # Callback to handle _entry_1 widget option -invalidcommand
    def _entry_1_invalidcommand(self, *args):
        pass

    # _entry_1_validatecommand --
    #
    # Callback to handle _entry_1 widget option -validatecommand
    def _entry_1_validatecommand(self, *args):
        pass

    # _entry_1_xscrollcommand --
    #
    # Callback to handle _entry_1 widget option -xscrollcommand
    def _entry_1_xscrollcommand(self, *args):
        pass

    # _entry_2_invalidcommand --
    #
    # Callback to handle _entry_2 widget option -invalidcommand
    def _entry_2_invalidcommand(self, *args):
        pass

    # _entry_2_validatecommand --
    #
    # Callback to handle _entry_2 widget option -validatecommand
    def _entry_2_validatecommand(self, *args):
        pass

    # _entry_2_xscrollcommand --
    #
    # Callback to handle _entry_2 widget option -xscrollcommand
    def _entry_2_xscrollcommand(self, *args):
        pass

    # _text_2_xscrollcommand --
    #
    # Callback to handle _text_2 widget option -xscrollcommand
    def _text_2_xscrollcommand(self, *args):
        pass

    # _text_2_yscrollcommand --
    #
    # Callback to handle _text_2 widget option -yscrollcommand
    def _text_2_yscrollcommand(self, *args):
        pass

    # _text_3_xscrollcommand --
    #
    # Callback to handle _text_3 widget option -xscrollcommand
    def _text_3_xscrollcommand(self, *args):
        pass

    # _text_3_yscrollcommand --
    #
    # Callback to handle _text_3 widget option -yscrollcommand
    def _text_3_yscrollcommand(self, *args):
        pass

    # _radiobutton_1_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _radiobutton_1_command(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomBase_GUI(root)
    root.title('base_GUI')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
