""" base_GUI_ui.py --

UI generated by GUI Builder Build 146 on 2018-04-23 10:26:02 from:
C:/Users/chris/Desktop/CYEN PROJ/base_GUI.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
from Tkinter import *
import os

class TediouSMS_UI(object):

	_images = [] # Holds image refs to prevent GC
	
	def __init__(self, root):

		# Widget Initialization
		self.sending_label = Tkinter.Label(root,
			font = "{MS Sans Serif} 14 bold",
			text = "Sending",
		)
		
		self.receiving_label = Tkinter.Label(root,
			font = "{MS Sans Serif} 14 bold",
			text = "Receiving",
		)

		self.send_button = Tkinter.Button(root,
			font = "{MS Sans Serif} 14 bold",
			text = "SEND",
		)
		
		self.recipient_ip_entry_field = Tkinter.Entry(root,
			width = 0,
		)
		
		self.recipient_ip_address_label = Tkinter.Label(root,
			font = "{MS Sans Serif} 12",
			text = "Recipient IP Address",
		)
		
		self.user_ip_address_label = Tkinter.Label(root,
			font = "{MS Sans Serif} 12",
			text = "Your IP Address",
		)
		
		self.outbound_message_textbox = Tkinter.Text(root,
			height = 0,
			width = 0,
		)
				
		self.inbound_message_texbox = Tkinter.Text(root,
			height = 0,
			width = 0,
		)
		
		self.user_ip_entry_field = Tkinter.Entry(root,
			width = 0,
		)
		
		self.listening_checkbox = Tkinter.Checkbutton(root,
			font = "{MS Sans Serif} 12 bold",
			text = "Listening on IP",
		)

		# widget commands
		
		self.send_button.configure(
			command = self.on_send_button_clicked
		)
		
		self.recipient_ip_entry_field.configure(
			invalidcommand = self.recipient_ip_entry_field_invalidcommand
		)
		
		self.recipient_ip_entry_field.configure(
			validatecommand = self.recipient_ip_entry_field_validatecommand
		)
		
		self.recipient_ip_entry_field.configure(
			xscrollcommand = self.recipient_ip_entry_field_xscrollcommand
		)
		
		self.user_ip_entry_field.configure(
			invalidcommand = self.user_ip_entry_field_invalidcommand
		)
		
		self.user_ip_entry_field.configure(
			validatecommand = self.user_ip_entry_field_validatecommand
		)
		
		self.user_ip_entry_field.configure(
			xscrollcommand = self.user_ip_entry_field_xscrollcommand
		)
		
		self.outbound_message_textbox.configure(
			xscrollcommand = self.outbound_message_textbox_xscrollcommand
		)
		
		self.outbound_message_textbox.configure(
			yscrollcommand = self.outbound_message_textbox_yscrollcommand
		)
		
		self.inbound_message_texbox.configure(
			xscrollcommand = self.inbound_message_texbox_xscrollcommand
		)
		
		self.inbound_message_texbox.configure(
			yscrollcommand = self.inbound_message_texbox_yscrollcommand
		)

		self.listening_checkbox.configure(
			command = self.listening_checkbox_command
		)
		
		# Geometry Management
		self.sending_label.grid(
			in_    = root,
			column = 1,
			row    = 1,
			columnspan = 1,
			ipadx = 0,
			ipady = 0,
			padx = 0,
			pady = 0,
			rowspan = 1,
			sticky = ""
		)
		
		self.receiving_label.grid(
			in_    = root,
			column = 2,
			row    = 1,
			columnspan = 1,
			ipadx = 0,
			ipady = 0,
			padx = 0,
			pady = 0,
			rowspan = 1,
			sticky = ""
		)
		
		self.send_button.grid(
			in_    = root,
			column = 1,
			row    = 3,
			columnspan = 1,
			ipadx = 0,
			ipady = 0,
			padx = 0,
			pady = 0,
			rowspan = 1,
			sticky = ""
		)
		
		self.recipient_ip_entry_field.grid(
			in_    = root,
			column = 2,
			row    = 5,
			columnspan = 1,
			ipadx = 0,
			ipady = 0,
			padx = 0,
			pady = 0,
			rowspan = 1,
			sticky = "ew"
		)
		
		self.recipient_ip_address_label.grid(
			in_    = root,
			column = 2,
			row    = 4,
			columnspan = 1,
			ipadx = 0,
			ipady = 0,
			padx = 0,
			pady = 0,
			rowspan = 1,
			sticky = ""
		)
		
		self.user_ip_address_label.grid(
			in_    = root,
			column = 1,
			row    = 4,
			columnspan = 1,
			ipadx = 0,
			ipady = 0,
			padx = 0,
			pady = 0,
			rowspan = 1,
			sticky = ""
		)
		
		self.outbound_message_textbox.grid(
			in_    = root,
			column = 1,
			row    = 2,
			columnspan = 1,
			ipadx = 0,
			ipady = 0,
			padx = 0,
			pady = 0,
			rowspan = 1,
			sticky = "news"
		)
		
		self.inbound_message_texbox.grid(
			in_    = root,
			column = 2,
			row    = 2,
			columnspan = 1,
			ipadx = 0,
			ipady = 0,
			padx = 0,
			pady = 0,
			rowspan = 1,
			sticky = "news"
		)
		
		self.user_ip_entry_field.grid(
			in_    = root,
			column = 1,
			row    = 5,
			columnspan = 1,
			ipadx = 0,
			ipady = 0,
			padx = 0,
			pady = 0,
			rowspan = 1,
			sticky = "ew"
		)
		
		self.listening_checkbox.grid(
			in_    = root,
			column = 2,
			row    = 3,
			columnspan = 1,
			ipadx = 0,
			ipady = 0,
			padx = 0,
			pady = 0,
			rowspan = 1,
			sticky = ""
		)

		# Resize Behavior
		root.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
		root.grid_rowconfigure(2, weight = 0, minsize = 133, pad = 0)
		root.grid_rowconfigure(3, weight = 0, minsize = 102, pad = 0)
		root.grid_rowconfigure(4, weight = 0, minsize = 21, pad = 0)
		root.grid_rowconfigure(5, weight = 0, minsize = 30, pad = 0)
		root.grid_rowconfigure(6, weight = 0, minsize = 2, pad = 0)
		root.grid_columnconfigure(1, weight = 0, minsize = 538, pad = 0)
		root.grid_columnconfigure(2, weight = 0, minsize = 538, pad = 0)




