""" base_GUI.py --

 UI generated by GUI Builder Build 146 on 2018-04-23 10:26:02 from:
    C:/Users/chris/Desktop/CYEN PROJ/base_GUI.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from tsmsui import TediouSMS_UI

class TediouSMS_UI_Callback(TediouSMS_UI):
    
	def on_send_button_clicked(self, *args):
		print(args)
		
	def recipient_ip_entry_field_invalidcommand(self, *args):
		print(args)
		
	def recipient_ip_entry_field_validatecommand(self, *args):
		print(args)
		
	def recipient_ip_entry_field_xscrollcommand(self, *args):
		print(args)
		
	def user_ip_entry_field_invalidcommand(self, *args):
		print(args)
		
	def user_ip_entry_field_validatecommand(self, *args):
		print(args)
		
	def user_ip_entry_field_xscrollcommand(self, *args):
		print(args)

	def outbound_message_textbox_xscrollcommand(self, *args):
		print(args)
		
	def outbound_message_textbox_yscrollcommand(self, *args):
		print(args)
		
	def inbound_message_texbox_xscrollcommand(self, *args):
		print(args)
		
	def inbound_message_texbox_yscrollcommand(self, *args):
		print(args)
		
	def listening_checkbox_command(self, *args):
		print(args)
	
def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    root = Tk()
    demo = TediouSMS_UI(root)
    root.title('tsmsui')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
